### ISSUE TITLE
[bug] [compat] Modded GUI components disappear.

### ISSUE THREAD

**Issue by noawx** [Cheos137/libhud-fabric#4]
Minecraft: 1.20.1
Fabric Loader: 0.14.21
When libhud is enabled, the minimaps disappear on both Journeymap and Xaero's Minimap.

**Comment by Cheos137** [comment]
to be expected as libhud provides a platform mods *can* use to be compatible with each other
thus, libhud will make no efforts to add compatibility for 3rd party mods - actually more or less the opposite is expected (if anything)
